<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

?>

<div class="options_group hide_if_variable hide_if_grouped">
	<h4 style="padding-left:12px;"><?php esc_html_e('FreeAgent Invoice settings', 'wc-freeagent'); ?></h4>
  <?php
  woocommerce_wp_select(array(
		'options'  => array(
			'' => __('-no unit-', 'wc-freeagent'),
			'Hours' => __('Hours', 'wc-freeagent'),
			'Days' => __('Days', 'wc-freeagent'),
			'Weeks' => __('Weeks', 'wc-freeagent'),
			'Months' => __('Months', 'wc-freeagent'),
			'Years' => __('Years', 'wc-freeagent'),
			'Products' => __('Products', 'wc-freeagent'),
			'Services' => __('Services', 'wc-freeagent'),
			'Training' => __('Training', 'wc-freeagent'),
			'Expenses' => __('Expenses', 'wc-freeagent'),
			'Comment' => __('Comment', 'wc-freeagent'),
			'Bills' => __('Bills', 'wc-freeagent'),
			'Discount' => __('Discount', 'wc-freeagent'),
			'Credit' => __('Credit', 'wc-freeagent'),
		),
    'id' => 'wc_freeagent_line_item_unit',
    'label' => esc_html__('Unit', 'wc-freeagent'),
    'desc_tip' => true,
    'value' => esc_attr( $post->wc_freeagent_line_item_unit ),
    'description' => esc_html__('The line item unit visible on the invoice generated by FreeAgent. If the fields is empty, it will use the default value set in the settings.', 'wc-freeagent')
  ));
  ?>
  <?php
  woocommerce_wp_text_input(array(
    'id' => 'wc_freeagent_line_item_desc',
    'label' => esc_html__('Line item note', 'wc-freeagent'),
    'desc_tip' => true,
    'value' => esc_attr( $post->wc_freeagent_line_item_desc ),
    'description' => esc_html__('Additional text below the line item on the invoice.', 'wc-freeagent')
  ));
  ?>
	<?php
		woocommerce_wp_text_input(array(
			'id' => 'wc_freeagent_line_item_name',
			'label' => esc_html__('Line item name', 'wc-freeagent'),
			'desc_tip' => true,
			'value' => esc_attr( $post->wc_freeagent_line_item_name ),
			'description' => esc_html__('You can change the invoice line item name here(default is the product name).', 'wc-freeagent')
		));
	?>
</div>
